#include <arch/x86/idt.h>
#include <out.h>
#include <virt_mem.h>
#include <page.h>
#include <interrupt.h>

IDTEntry __attribute__((aligned(SMALL_PAGE_SIZE))) idt[IDT_NUM_ENTRIES];

IDTEntry_t IDTEntry::New() {
    // Returns a new empty IDTEntry
    return IDTEntry {
        .addr_low = 0,
        .selector = KERNEL_CS,
        .options = IDT_OPTION_DEFAULT,
        .addr_mid = 0,
        .addr_high = 0,
        .reserved = 0,
    };
}

void IDTEntry::set_addr (u64 new_addr) {
    addr_low = new_addr;
    addr_mid = (new_addr >> 16);
    addr_high = (new_addr >> 32);
}

void IDTEntry::enable_interrupts() {
    options &= ~IDT_OPTION_TYPE_MASK;
    options |= IDT_OPTION_TYPE_INT_GATE;
}

void IDTEntry::disable_interrupts() {
    options &= ~IDT_OPTION_TYPE_MASK;
    options |= IDT_OPTION_TYPE_TRAP_GATE;
}

void IDTEntry::set_present(bool present) {
    options &= ~IDT_OPTION_PRESENT_MASK;
    if (present) options |= IDT_OPTION_PRESENT;
}

void IDTEntry::set_dpl(Selector dpl) {
    options &= ~IDT_OPTION_DPL_MASK;
    options |= dpl << IDT_OPTION_DPL_SHIFT;
}

extern "C" {
extern void __unknown_int_0();
extern void __unknown_int_1();
extern void __unknown_int_2();
extern void __unknown_int_3();
extern void __unknown_int_4();
extern void __unknown_int_5();
extern void __unknown_int_6();
extern void __unknown_int_7();
extern void __unknown_int_8();
extern void __unknown_int_9();
extern void __unknown_int_10();
extern void __unknown_int_11();
extern void __unknown_int_12();
extern void __unknown_int_13();
extern void __unknown_int_14();
extern void __unknown_int_15();
extern void __unknown_int_16();
extern void __unknown_int_17();
extern void __unknown_int_18();
extern void __unknown_int_19();
extern void __unknown_int_20();
extern void __unknown_int_21();
extern void __unknown_int_22();
extern void __unknown_int_23();
extern void __unknown_int_24();
extern void __unknown_int_25();
extern void __unknown_int_26();
extern void __unknown_int_27();
extern void __unknown_int_28();
extern void __unknown_int_29();
extern void __unknown_int_30();
extern void __unknown_int_31();
extern void __unknown_int_32();
extern void __unknown_int_33();
extern void __unknown_int_34();
extern void __unknown_int_35();
extern void __unknown_int_36();
extern void __unknown_int_37();
extern void __unknown_int_38();
extern void __unknown_int_39();
extern void __unknown_int_40();
extern void __unknown_int_41();
extern void __unknown_int_42();
extern void __unknown_int_43();
extern void __unknown_int_44();
extern void __unknown_int_45();
extern void __unknown_int_46();
extern void __unknown_int_47();
extern void __unknown_int_48();
extern void __unknown_int_49();
extern void __unknown_int_50();
extern void __unknown_int_51();
extern void __unknown_int_52();
extern void __unknown_int_53();
extern void __unknown_int_54();
extern void __unknown_int_55();
extern void __unknown_int_56();
extern void __unknown_int_57();
extern void __unknown_int_58();
extern void __unknown_int_59();
extern void __unknown_int_60();
extern void __unknown_int_61();
extern void __unknown_int_62();
extern void __unknown_int_63();
extern void __unknown_int_64();
extern void __unknown_int_65();
extern void __unknown_int_66();
extern void __unknown_int_67();
extern void __unknown_int_68();
extern void __unknown_int_69();
extern void __unknown_int_70();
extern void __unknown_int_71();
extern void __unknown_int_72();
extern void __unknown_int_73();
extern void __unknown_int_74();
extern void __unknown_int_75();
extern void __unknown_int_76();
extern void __unknown_int_77();
extern void __unknown_int_78();
extern void __unknown_int_79();
extern void __unknown_int_80();
extern void __unknown_int_81();
extern void __unknown_int_82();
extern void __unknown_int_83();
extern void __unknown_int_84();
extern void __unknown_int_85();
extern void __unknown_int_86();
extern void __unknown_int_87();
extern void __unknown_int_88();
extern void __unknown_int_89();
extern void __unknown_int_90();
extern void __unknown_int_91();
extern void __unknown_int_92();
extern void __unknown_int_93();
extern void __unknown_int_94();
extern void __unknown_int_95();
extern void __unknown_int_96();
extern void __unknown_int_97();
extern void __unknown_int_98();
extern void __unknown_int_99();
extern void __unknown_int_100();
extern void __unknown_int_101();
extern void __unknown_int_102();
extern void __unknown_int_103();
extern void __unknown_int_104();
extern void __unknown_int_105();
extern void __unknown_int_106();
extern void __unknown_int_107();
extern void __unknown_int_108();
extern void __unknown_int_109();
extern void __unknown_int_110();
extern void __unknown_int_111();
extern void __unknown_int_112();
extern void __unknown_int_113();
extern void __unknown_int_114();
extern void __unknown_int_115();
extern void __unknown_int_116();
extern void __unknown_int_117();
extern void __unknown_int_118();
extern void __unknown_int_119();
extern void __unknown_int_120();
extern void __unknown_int_121();
extern void __unknown_int_122();
extern void __unknown_int_123();
extern void __unknown_int_124();
extern void __unknown_int_125();
extern void __unknown_int_126();
extern void __unknown_int_127();
extern void __unknown_int_128();
extern void __unknown_int_129();
extern void __unknown_int_130();
extern void __unknown_int_131();
extern void __unknown_int_132();
extern void __unknown_int_133();
extern void __unknown_int_134();
extern void __unknown_int_135();
extern void __unknown_int_136();
extern void __unknown_int_137();
extern void __unknown_int_138();
extern void __unknown_int_139();
extern void __unknown_int_140();
extern void __unknown_int_141();
extern void __unknown_int_142();
extern void __unknown_int_143();
extern void __unknown_int_144();
extern void __unknown_int_145();
extern void __unknown_int_146();
extern void __unknown_int_147();
extern void __unknown_int_148();
extern void __unknown_int_149();
extern void __unknown_int_150();
extern void __unknown_int_151();
extern void __unknown_int_152();
extern void __unknown_int_153();
extern void __unknown_int_154();
extern void __unknown_int_155();
extern void __unknown_int_156();
extern void __unknown_int_157();
extern void __unknown_int_158();
extern void __unknown_int_159();
extern void __unknown_int_160();
extern void __unknown_int_161();
extern void __unknown_int_162();
extern void __unknown_int_163();
extern void __unknown_int_164();
extern void __unknown_int_165();
extern void __unknown_int_166();
extern void __unknown_int_167();
extern void __unknown_int_168();
extern void __unknown_int_169();
extern void __unknown_int_170();
extern void __unknown_int_171();
extern void __unknown_int_172();
extern void __unknown_int_173();
extern void __unknown_int_174();
extern void __unknown_int_175();
extern void __unknown_int_176();
extern void __unknown_int_177();
extern void __unknown_int_178();
extern void __unknown_int_179();
extern void __unknown_int_180();
extern void __unknown_int_181();
extern void __unknown_int_182();
extern void __unknown_int_183();
extern void __unknown_int_184();
extern void __unknown_int_185();
extern void __unknown_int_186();
extern void __unknown_int_187();
extern void __unknown_int_188();
extern void __unknown_int_189();
extern void __unknown_int_190();
extern void __unknown_int_191();
extern void __unknown_int_192();
extern void __unknown_int_193();
extern void __unknown_int_194();
extern void __unknown_int_195();
extern void __unknown_int_196();
extern void __unknown_int_197();
extern void __unknown_int_198();
extern void __unknown_int_199();
extern void __unknown_int_200();
extern void __unknown_int_201();
extern void __unknown_int_202();
extern void __unknown_int_203();
extern void __unknown_int_204();
extern void __unknown_int_205();
extern void __unknown_int_206();
extern void __unknown_int_207();
extern void __unknown_int_208();
extern void __unknown_int_209();
extern void __unknown_int_210();
extern void __unknown_int_211();
extern void __unknown_int_212();
extern void __unknown_int_213();
extern void __unknown_int_214();
extern void __unknown_int_215();
extern void __unknown_int_216();
extern void __unknown_int_217();
extern void __unknown_int_218();
extern void __unknown_int_219();
extern void __unknown_int_220();
extern void __unknown_int_221();
extern void __unknown_int_222();
extern void __unknown_int_223();
extern void __unknown_int_224();
extern void __unknown_int_225();
extern void __unknown_int_226();
extern void __unknown_int_227();
extern void __unknown_int_228();
extern void __unknown_int_229();
extern void __unknown_int_230();
extern void __unknown_int_231();
extern void __unknown_int_232();
extern void __unknown_int_233();
extern void __unknown_int_234();
extern void __unknown_int_235();
extern void __unknown_int_236();
extern void __unknown_int_237();
extern void __unknown_int_238();
extern void __unknown_int_239();
extern void __unknown_int_240();
extern void __unknown_int_241();
extern void __unknown_int_242();
extern void __unknown_int_243();
extern void __unknown_int_244();
extern void __unknown_int_245();
extern void __unknown_int_246();
extern void __unknown_int_247();
extern void __unknown_int_248();
extern void __unknown_int_249();
extern void __unknown_int_250();
extern void __unknown_int_251();
extern void __unknown_int_252();
extern void __unknown_int_253();
extern void __unknown_int_254();
extern void __unknown_int_255();
}

void InitIDT() {
    for (usize i = 0; i < IDT_NUM_ENTRIES; i++) {
        idt[i] = IDTEntry::New();
    }

    idt[0].set_addr((usize)&__unknown_int_0);
    idt[1].set_addr((usize)&__unknown_int_1);
    idt[2].set_addr((usize)&__unknown_int_2);
    idt[3].set_addr((usize)&__unknown_int_3);
    idt[4].set_addr((usize)&__unknown_int_4);
    idt[5].set_addr((usize)&__unknown_int_5);
    idt[6].set_addr((usize)&__unknown_int_6);
    idt[7].set_addr((usize)&__unknown_int_7);
    idt[8].set_addr((usize)&__unknown_int_8);
    idt[9].set_addr((usize)&__unknown_int_9);
    idt[10].set_addr((usize)&__unknown_int_10);
    idt[11].set_addr((usize)&__unknown_int_11);
    idt[12].set_addr((usize)&__unknown_int_12);
    idt[13].set_addr((usize)&__unknown_int_13);
    idt[14].set_addr((usize)&__unknown_int_14);
    idt[15].set_addr((usize)&__unknown_int_15);
    idt[16].set_addr((usize)&__unknown_int_16);
    idt[17].set_addr((usize)&__unknown_int_17);
    idt[18].set_addr((usize)&__unknown_int_18);
    idt[19].set_addr((usize)&__unknown_int_19);
    idt[20].set_addr((usize)&__unknown_int_20);
    idt[21].set_addr((usize)&__unknown_int_21);
    idt[22].set_addr((usize)&__unknown_int_22);
    idt[23].set_addr((usize)&__unknown_int_23);
    idt[24].set_addr((usize)&__unknown_int_24);
    idt[25].set_addr((usize)&__unknown_int_25);
    idt[26].set_addr((usize)&__unknown_int_26);
    idt[27].set_addr((usize)&__unknown_int_27);
    idt[28].set_addr((usize)&__unknown_int_28);
    idt[29].set_addr((usize)&__unknown_int_29);
    idt[30].set_addr((usize)&__unknown_int_30);
    idt[31].set_addr((usize)&__unknown_int_31);
    idt[32].set_addr((usize)&__unknown_int_32);
    idt[33].set_addr((usize)&__unknown_int_33);
    idt[34].set_addr((usize)&__unknown_int_34);
    idt[35].set_addr((usize)&__unknown_int_35);
    idt[36].set_addr((usize)&__unknown_int_36);
    idt[37].set_addr((usize)&__unknown_int_37);
    idt[38].set_addr((usize)&__unknown_int_38);
    idt[39].set_addr((usize)&__unknown_int_39);
    idt[40].set_addr((usize)&__unknown_int_40);
    idt[41].set_addr((usize)&__unknown_int_41);
    idt[42].set_addr((usize)&__unknown_int_42);
    idt[43].set_addr((usize)&__unknown_int_43);
    idt[44].set_addr((usize)&__unknown_int_44);
    idt[45].set_addr((usize)&__unknown_int_45);
    idt[46].set_addr((usize)&__unknown_int_46);
    idt[47].set_addr((usize)&__unknown_int_47);
    idt[48].set_addr((usize)&__unknown_int_48);
    idt[49].set_addr((usize)&__unknown_int_49);
    idt[50].set_addr((usize)&__unknown_int_50);
    idt[51].set_addr((usize)&__unknown_int_51);
    idt[52].set_addr((usize)&__unknown_int_52);
    idt[53].set_addr((usize)&__unknown_int_53);
    idt[54].set_addr((usize)&__unknown_int_54);
    idt[55].set_addr((usize)&__unknown_int_55);
    idt[56].set_addr((usize)&__unknown_int_56);
    idt[57].set_addr((usize)&__unknown_int_57);
    idt[58].set_addr((usize)&__unknown_int_58);
    idt[59].set_addr((usize)&__unknown_int_59);
    idt[60].set_addr((usize)&__unknown_int_60);
    idt[61].set_addr((usize)&__unknown_int_61);
    idt[62].set_addr((usize)&__unknown_int_62);
    idt[63].set_addr((usize)&__unknown_int_63);
    idt[64].set_addr((usize)&__unknown_int_64);
    idt[65].set_addr((usize)&__unknown_int_65);
    idt[66].set_addr((usize)&__unknown_int_66);
    idt[67].set_addr((usize)&__unknown_int_67);
    idt[68].set_addr((usize)&__unknown_int_68);
    idt[69].set_addr((usize)&__unknown_int_69);
    idt[70].set_addr((usize)&__unknown_int_70);
    idt[71].set_addr((usize)&__unknown_int_71);
    idt[72].set_addr((usize)&__unknown_int_72);
    idt[73].set_addr((usize)&__unknown_int_73);
    idt[74].set_addr((usize)&__unknown_int_74);
    idt[75].set_addr((usize)&__unknown_int_75);
    idt[76].set_addr((usize)&__unknown_int_76);
    idt[77].set_addr((usize)&__unknown_int_77);
    idt[78].set_addr((usize)&__unknown_int_78);
    idt[79].set_addr((usize)&__unknown_int_79);
    idt[80].set_addr((usize)&__unknown_int_80);
    idt[81].set_addr((usize)&__unknown_int_81);
    idt[82].set_addr((usize)&__unknown_int_82);
    idt[83].set_addr((usize)&__unknown_int_83);
    idt[84].set_addr((usize)&__unknown_int_84);
    idt[85].set_addr((usize)&__unknown_int_85);
    idt[86].set_addr((usize)&__unknown_int_86);
    idt[87].set_addr((usize)&__unknown_int_87);
    idt[88].set_addr((usize)&__unknown_int_88);
    idt[89].set_addr((usize)&__unknown_int_89);
    idt[90].set_addr((usize)&__unknown_int_90);
    idt[91].set_addr((usize)&__unknown_int_91);
    idt[92].set_addr((usize)&__unknown_int_92);
    idt[93].set_addr((usize)&__unknown_int_93);
    idt[94].set_addr((usize)&__unknown_int_94);
    idt[95].set_addr((usize)&__unknown_int_95);
    idt[96].set_addr((usize)&__unknown_int_96);
    idt[97].set_addr((usize)&__unknown_int_97);
    idt[98].set_addr((usize)&__unknown_int_98);
    idt[99].set_addr((usize)&__unknown_int_99);
    idt[100].set_addr((usize)&__unknown_int_100);
    idt[101].set_addr((usize)&__unknown_int_101);
    idt[102].set_addr((usize)&__unknown_int_102);
    idt[103].set_addr((usize)&__unknown_int_103);
    idt[104].set_addr((usize)&__unknown_int_104);
    idt[105].set_addr((usize)&__unknown_int_105);
    idt[106].set_addr((usize)&__unknown_int_106);
    idt[107].set_addr((usize)&__unknown_int_107);
    idt[108].set_addr((usize)&__unknown_int_108);
    idt[109].set_addr((usize)&__unknown_int_109);
    idt[110].set_addr((usize)&__unknown_int_110);
    idt[111].set_addr((usize)&__unknown_int_111);
    idt[112].set_addr((usize)&__unknown_int_112);
    idt[113].set_addr((usize)&__unknown_int_113);
    idt[114].set_addr((usize)&__unknown_int_114);
    idt[115].set_addr((usize)&__unknown_int_115);
    idt[116].set_addr((usize)&__unknown_int_116);
    idt[117].set_addr((usize)&__unknown_int_117);
    idt[118].set_addr((usize)&__unknown_int_118);
    idt[119].set_addr((usize)&__unknown_int_119);
    idt[120].set_addr((usize)&__unknown_int_120);
    idt[121].set_addr((usize)&__unknown_int_121);
    idt[122].set_addr((usize)&__unknown_int_122);
    idt[123].set_addr((usize)&__unknown_int_123);
    idt[124].set_addr((usize)&__unknown_int_124);
    idt[125].set_addr((usize)&__unknown_int_125);
    idt[126].set_addr((usize)&__unknown_int_126);
    idt[127].set_addr((usize)&__unknown_int_127);
    idt[128].set_addr((usize)&__unknown_int_128);
    idt[129].set_addr((usize)&__unknown_int_129);
    idt[130].set_addr((usize)&__unknown_int_130);
    idt[131].set_addr((usize)&__unknown_int_131);
    idt[132].set_addr((usize)&__unknown_int_132);
    idt[133].set_addr((usize)&__unknown_int_133);
    idt[134].set_addr((usize)&__unknown_int_134);
    idt[135].set_addr((usize)&__unknown_int_135);
    idt[136].set_addr((usize)&__unknown_int_136);
    idt[137].set_addr((usize)&__unknown_int_137);
    idt[138].set_addr((usize)&__unknown_int_138);
    idt[139].set_addr((usize)&__unknown_int_139);
    idt[140].set_addr((usize)&__unknown_int_140);
    idt[141].set_addr((usize)&__unknown_int_141);
    idt[142].set_addr((usize)&__unknown_int_142);
    idt[143].set_addr((usize)&__unknown_int_143);
    idt[144].set_addr((usize)&__unknown_int_144);
    idt[145].set_addr((usize)&__unknown_int_145);
    idt[146].set_addr((usize)&__unknown_int_146);
    idt[147].set_addr((usize)&__unknown_int_147);
    idt[148].set_addr((usize)&__unknown_int_148);
    idt[149].set_addr((usize)&__unknown_int_149);
    idt[150].set_addr((usize)&__unknown_int_150);
    idt[151].set_addr((usize)&__unknown_int_151);
    idt[152].set_addr((usize)&__unknown_int_152);
    idt[153].set_addr((usize)&__unknown_int_153);
    idt[154].set_addr((usize)&__unknown_int_154);
    idt[155].set_addr((usize)&__unknown_int_155);
    idt[156].set_addr((usize)&__unknown_int_156);
    idt[157].set_addr((usize)&__unknown_int_157);
    idt[158].set_addr((usize)&__unknown_int_158);
    idt[159].set_addr((usize)&__unknown_int_159);
    idt[160].set_addr((usize)&__unknown_int_160);
    idt[161].set_addr((usize)&__unknown_int_161);
    idt[162].set_addr((usize)&__unknown_int_162);
    idt[163].set_addr((usize)&__unknown_int_163);
    idt[164].set_addr((usize)&__unknown_int_164);
    idt[165].set_addr((usize)&__unknown_int_165);
    idt[166].set_addr((usize)&__unknown_int_166);
    idt[167].set_addr((usize)&__unknown_int_167);
    idt[168].set_addr((usize)&__unknown_int_168);
    idt[169].set_addr((usize)&__unknown_int_169);
    idt[170].set_addr((usize)&__unknown_int_170);
    idt[171].set_addr((usize)&__unknown_int_171);
    idt[172].set_addr((usize)&__unknown_int_172);
    idt[173].set_addr((usize)&__unknown_int_173);
    idt[174].set_addr((usize)&__unknown_int_174);
    idt[175].set_addr((usize)&__unknown_int_175);
    idt[176].set_addr((usize)&__unknown_int_176);
    idt[177].set_addr((usize)&__unknown_int_177);
    idt[178].set_addr((usize)&__unknown_int_178);
    idt[179].set_addr((usize)&__unknown_int_179);
    idt[180].set_addr((usize)&__unknown_int_180);
    idt[181].set_addr((usize)&__unknown_int_181);
    idt[182].set_addr((usize)&__unknown_int_182);
    idt[183].set_addr((usize)&__unknown_int_183);
    idt[184].set_addr((usize)&__unknown_int_184);
    idt[185].set_addr((usize)&__unknown_int_185);
    idt[186].set_addr((usize)&__unknown_int_186);
    idt[187].set_addr((usize)&__unknown_int_187);
    idt[188].set_addr((usize)&__unknown_int_188);
    idt[189].set_addr((usize)&__unknown_int_189);
    idt[190].set_addr((usize)&__unknown_int_190);
    idt[191].set_addr((usize)&__unknown_int_191);
    idt[192].set_addr((usize)&__unknown_int_192);
    idt[193].set_addr((usize)&__unknown_int_193);
    idt[194].set_addr((usize)&__unknown_int_194);
    idt[195].set_addr((usize)&__unknown_int_195);
    idt[196].set_addr((usize)&__unknown_int_196);
    idt[197].set_addr((usize)&__unknown_int_197);
    idt[198].set_addr((usize)&__unknown_int_198);
    idt[199].set_addr((usize)&__unknown_int_199);
    idt[200].set_addr((usize)&__unknown_int_200);
    idt[201].set_addr((usize)&__unknown_int_201);
    idt[202].set_addr((usize)&__unknown_int_202);
    idt[203].set_addr((usize)&__unknown_int_203);
    idt[204].set_addr((usize)&__unknown_int_204);
    idt[205].set_addr((usize)&__unknown_int_205);
    idt[206].set_addr((usize)&__unknown_int_206);
    idt[207].set_addr((usize)&__unknown_int_207);
    idt[208].set_addr((usize)&__unknown_int_208);
    idt[209].set_addr((usize)&__unknown_int_209);
    idt[210].set_addr((usize)&__unknown_int_210);
    idt[211].set_addr((usize)&__unknown_int_211);
    idt[212].set_addr((usize)&__unknown_int_212);
    idt[213].set_addr((usize)&__unknown_int_213);
    idt[214].set_addr((usize)&__unknown_int_214);
    idt[215].set_addr((usize)&__unknown_int_215);
    idt[216].set_addr((usize)&__unknown_int_216);
    idt[217].set_addr((usize)&__unknown_int_217);
    idt[218].set_addr((usize)&__unknown_int_218);
    idt[219].set_addr((usize)&__unknown_int_219);
    idt[220].set_addr((usize)&__unknown_int_220);
    idt[221].set_addr((usize)&__unknown_int_221);
    idt[222].set_addr((usize)&__unknown_int_222);
    idt[223].set_addr((usize)&__unknown_int_223);
    idt[224].set_addr((usize)&__unknown_int_224);
    idt[225].set_addr((usize)&__unknown_int_225);
    idt[226].set_addr((usize)&__unknown_int_226);
    idt[227].set_addr((usize)&__unknown_int_227);
    idt[228].set_addr((usize)&__unknown_int_228);
    idt[229].set_addr((usize)&__unknown_int_229);
    idt[230].set_addr((usize)&__unknown_int_230);
    idt[231].set_addr((usize)&__unknown_int_231);
    idt[232].set_addr((usize)&__unknown_int_232);
    idt[233].set_addr((usize)&__unknown_int_233);
    idt[234].set_addr((usize)&__unknown_int_234);
    idt[235].set_addr((usize)&__unknown_int_235);
    idt[236].set_addr((usize)&__unknown_int_236);
    idt[237].set_addr((usize)&__unknown_int_237);
    idt[238].set_addr((usize)&__unknown_int_238);
    idt[239].set_addr((usize)&__unknown_int_239);
    idt[240].set_addr((usize)&__unknown_int_240);
    idt[241].set_addr((usize)&__unknown_int_241);
    idt[242].set_addr((usize)&__unknown_int_242);
    idt[243].set_addr((usize)&__unknown_int_243);
    idt[244].set_addr((usize)&__unknown_int_244);
    idt[245].set_addr((usize)&__unknown_int_245);
    idt[246].set_addr((usize)&__unknown_int_246);
    idt[247].set_addr((usize)&__unknown_int_247);
    idt[248].set_addr((usize)&__unknown_int_248);
    idt[249].set_addr((usize)&__unknown_int_249);
    idt[250].set_addr((usize)&__unknown_int_250);
    idt[251].set_addr((usize)&__unknown_int_251);
    idt[252].set_addr((usize)&__unknown_int_252);
    idt[253].set_addr((usize)&__unknown_int_253);
    idt[254].set_addr((usize)&__unknown_int_254);
    idt[255].set_addr((usize)&__unknown_int_255);

    idt[UART0_IRQ].set_addr((usize)&uart0_irq);
    idt[APIC_TIMER_IRQ].set_addr((usize)&lapic_timer_irq);
    idt[VIRTIO_IRQ].set_addr((usize)&virtio_irq);

    idt[IDT_ILLEGAL_INST_EXCEPTION].set_addr((usize)&illegalinst_irq);
    idt[IDT_PAGEFAULT_EXCEPTION].set_addr((usize)&pagefault_irq);

    // Must mark this as volatile, otherwise O2 builds set idt incorrectly!
    volatile IDTPointer p = IDTPointer {
        .limit = (IDT_NUM_ENTRIES * sizeof(IDTEntry)) - 1,
        .addr = (u64)&idt,
    };

    asm volatile(
        "lidt [%0]"
        :: "r"((u64)&p)
    );
}
