#include <fractal.h>
#include <io/hid/input.h>
#include <io/hid/decode-keys.h>

// A look-up table mapping key codes to their ASCII representation
// This must be a C file because this bracket syntax does not work in C++
const char virtio_keymap[VIRTIO_KEYMAP_SIZE] = {
    [KEY_1] = '1',
    [KEY_2] = '2',
    [KEY_3] = '3',
    [KEY_4] = '4',
    [KEY_5] = '5',
    [KEY_6] = '6',
    [KEY_7] = '7',
    [KEY_8] = '8',
    [KEY_9] = '9',
    [KEY_0] = '0',
    [KEY_Q] = 'Q',
    [KEY_W] = 'W',
    [KEY_E] = 'E',
    [KEY_R] = 'R',
    [KEY_T] = 'T',
    [KEY_Y] = 'Y',
    [KEY_U] = 'U',
    [KEY_I] = 'I',
    [KEY_O] = 'O',
    [KEY_P] = 'P',
    [KEY_A] = 'A',
    [KEY_S] = 'S',
    [KEY_D] = 'D',
    [KEY_F] = 'F',
    [KEY_G] = 'G',
    [KEY_H] = 'H',
    [KEY_J] = 'J',
    [KEY_K] = 'K',
    [KEY_L] = 'L',
    [KEY_Z] = 'Z',
    [KEY_X] = 'X',
    [KEY_C] = 'C',
    [KEY_V] = 'V',
    [KEY_B] = 'B',
    [KEY_N] = 'N',
    [KEY_M] = 'M',
    [KEY_SPACE] = ' ',
    [KEY_LEFTBRACE] = '[',
    [KEY_RIGHTBRACE] = ']',
    [KEY_ENTER] = '\n',
    [KEY_BACKSPACE] = '\b',
    [KEY_DOT] = '.',
    [KEY_COMMA] = ',',
    [KEY_MINUS] = '-',
    [KEY_EQUAL] = '=',
    [KEY_SLASH] = '/',
    [KEY_GRAVE] = '`',
    [KEY_SEMICOLON] = ';',
    [KEY_APOSTROPHE] = '\'',
    [KEY_BACKSLASH] = '\\',
    [KEY_LEFT] = KEY_LEFT,
    [KEY_RIGHT] = KEY_RIGHT,
};