#ifndef X86_ASM_H
#define X86_ASM_H

#include <gen/x86_asm_offsets.h>

#define ARCH_HAS_FAST_MEMCPY
#define ARCH_HAS_FAST_MEMSET

#define KERNEL_LINK_ADDRESS 0xFFFF800000000000
#define INITRD_EXPECTED_ADDRESS 0xFFFF800003D14000

#define SERIAL_OUT_PORT 0x3F8

#define X86_IRET_CONTEXT_SIZE_WITHOUT_ERROR ((5 * 8))
#define X86_IRET_CONTEXT_SIZE_WITH_ERROR_AND_INTNUM ((7 * 8))
#define X86_IRET_CONTEXT_JUST_ERROR_AND_INTNUM_SIZE (((X86_IRET_CONTEXT_SIZE_WITH_ERROR_AND_INTNUM) - (X86_IRET_CONTEXT_SIZE_WITHOUT_ERROR)))

#define TIMESLICE_QUANTUM 0x80000

#define X86_RFLAGS_INTERRUPT_ENABLE_MASK ((1 << 9))

#define X86_RFLAGS_IOPL_FOR_USER         ((DPL_KERNEL << 12))

#define USER_RFLAG_START ((X86_RFLAGS_INTERRUPT_ENABLE_MASK | X86_RFLAGS_IOPL_FOR_USER))
#define KERNEL_RFLAG_START ((X86_RFLAGS_INTERRUPT_ENABLE_MASK))

#define USER_RFLAG_NO_INTERRUPTS ((X86_RFLAGS_IOPL_FOR_USER))
#define KERNEL_RFLAG_NO_INTERRUPTS ((0))

#define CR4_OSFXSR   ((1ull << 9))
#define CR4_FSGSBASE ((1ull << 16))

#define CR0_CACHE_DISABLE     ((1ull << 30))
#define CR0_WRITEBACK_DISABLE ((1ull << 29))

#define UART0_IRQ 36
#define VIRTIO_IRQ 37
#define APIC_TIMER_IRQ 55
#define LEGACY_KEYBOARD_IRQ 70
#define LEGACY_MOUSE_IRQ 71
#define X86_RESERVED_EXCEPTION 15

#define IDT_ILLEGAL_INST_EXCEPTION 6
#define IDT_PAGEFAULT_EXCEPTION 14

#endif // X86_ASM_H
